### ISSUE TITLE
How to export default modules?

### ISSUE THREAD

**Issue by boticello** [soegaard/urlang#18] opened 2019-01-04 01:10 UTC
I am hoping to use Urlang to write code for Gatsby. The Gatsby code examples use ES6 syntax. Gatsby pages and components export modules as default.

Is there a way in Urlang to export modules as default rather than named? I don't see any examples. I'm also inexperienced in both Javascript and Racket, so I may be missing something obvious.

**Comment by soegaard** [comment] 2019-01-05 17:47
Hi,

I took a look at Gatsby (which I had heard about before).

It looks complicated, so perhaps Urlang is not a good match - if something breaks
it will be difficult to track down, where the problem is.

Currently the output of Urlang is strictly ES5. I know that React works
with ES5 code, so maybe it's possible to get Gatsby working too.

The first step is to figure out how Gatsby can be used with ES5 and then
we can look at getting Urlang to generate the ES5 code.

/Jens Axel

**Comment by boticello** [comment] 2019-01-05 18:13
Thank you @soegaard for taking the time to look at Gatsby. 

It is complicated. It has its own magic and then there is the hairball complexity of modern JavaScript (webpack etc). But it is full-featured for its purpose.

I will do as you suggest - look at the code it generates in ES5 via Babel and see how to do the same in Urlang. As you suggest I may find that they are not the best fit together.

**Comment by soegaard** [comment] 2020-08-10 11:27
In the short term there will be no changes to the modules in Urlang.
There is some (not much, but some) support for ES6 modules now,
but the state of affair could be improved.

I am closing this for now - and will make a new one for "general improvement to
the module story".

**Closed by soegaard** 2020-08-10 11:27 UTC
